name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        working-directory: ./springbackend
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t nithyanandnadar/springbackend:latest .
          docker tag nithyanandnadar/springbackend:latest nithyanandnadar/springbackend:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push nithyanandnadar/springbackend:latest
          docker push nithyanandnadar/springbackend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull nithyanandnadar/springbackend:latest

      - name: Remove Old Container
        run: docker rm -f springbackend-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 5500:5000 \
            --name springbackend-container \
            nithyanandnadar/springbackend:latest
