name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and Test
        working-directory: ./springbackend
        run: mvn clean install

  Build_Docker_Image:
    needs: Build_and_Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        working-directory: ./springbackend
        run: |
          docker build -t nithyanandnadar/springbackend:${{ github.run_id }} .
          docker push nithyanandnadar/springbackend:${{ github.run_id }}

  Deploy_to_Production:
    needs: Build_Docker_Image
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull Docker Image
        run: docker pull nithyanandnadar/springbackend:${{ github.run_id }}
      - name: Remove Old Container
        run: docker rm -f springbackend-container || true
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 5500:5500 \
            --name springbackend-container \
            nithyanandnadar/springbackend:${{ github.run_id }}